/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diseasediagnosis;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Karol Abramczyk
 */
public class DiagnosisApp extends JFrame implements ActionListener{
    public static final String NEWLINE = "\n";
    
    public void log(String text, Color color) {
        logger.setForeground(color);
        logger.append(text);
    }
    
    public void logln(String text, Color color) {
        logger.setForeground(color);
        logger.append(text + NEWLINE);
    }
    
        /**
         * Main method of the application.
	 * @param args application call parameters.
	 */
	public static void main(String[] args) {
            try {
                    // Set System L&F
                UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
            } 
            catch (UnsupportedLookAndFeelException e) {
               // handle exception
            }
            catch (ClassNotFoundException e) {
               // handle exception
            }
            catch (InstantiationException e) {
               // handle exception
            }
            catch (IllegalAccessException e) {
               // handle exception
            }

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new DiagnosisApp().setVisible(true);
                }
            });
	}

    /**
     * Creates new form DiagnosisApp
     */
    public DiagnosisApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        logger = new javax.swing.JTextArea();
        questionField = new javax.swing.JTextField();
        questionField.addActionListener(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logger.setEditable(false);
        logger.setBackground(new java.awt.Color(153, 153, 153));
        logger.setColumns(20);
        logger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logger.setForeground(new java.awt.Color(0, 0, 0));
        logger.setRows(5);
        logger.setToolTipText("");
        jScrollPane1.setViewportView(logger);

        questionField.setBackground(new java.awt.Color(153, 153, 153));
        questionField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionField.setForeground(new java.awt.Color(0, 0, 0));
        questionField.setToolTipText("Your question here");
        questionField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Question", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                    .addComponent(questionField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logger;
    private javax.swing.JTextField questionField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        String text = questionField.getText();
        logln(text, Color.BLUE);
        questionField.selectAll();
    }
}
